import Link from "next/link";
import { ConfirmSubmitButton } from "@/components/confirm-submit-button";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createPayment, deleteAllPayments, deletePayment } from "@/features/payments/actions";
import { prisma } from "@/lib/prisma";
import { formatCurrency } from "@/lib/utils";

export default async function PaymentsPage() {
  const [payments, invoices] = await Promise.all([prisma.payment.findMany({ include: { invoice: true, client: true }, orderBy: { paidAt: "desc" } }), prisma.invoice.findMany({ where: { remainingAmount: { gt: 0 } }, include: { client: true }, orderBy: { issuedAt: "desc" } })]);
  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">Paiements</h1><p className="text-muted-foreground">Saisie des règlements et mise à jour automatique des factures.</p></div><form action={deleteAllPayments}><ConfirmSubmitButton message="Supprimer tous les paiements et recalculer les factures ?" variant="secondary" className="text-red-600">Supprimer tous</ConfirmSubmitButton></form></div><Card>{invoices.length > 0 ? <form action={createPayment} className="grid gap-3 md:grid-cols-5"><select name="invoiceId" className="h-10 rounded-lg border bg-card px-3 text-sm" required><option value="">Choisir une facture à encaisser</option>{invoices.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.number} - {invoice.client.legalName} - reste {formatCurrency(Number(invoice.remainingAmount))}</option>)}</select><Input name="amount" type="number" step="0.01" placeholder="Montant" required /><Input name="paidAt" type="date" required /><Input name="method" placeholder="Mode" defaultValue="Virement bancaire" required /><Button>Enregistrer</Button></form> : <div className="rounded-xl border border-dashed p-6 text-sm text-muted-foreground">Aucune facture avec un montant restant à encaisser. Crée une facture depuis <Link href="/sales/invoices/new" className="underline">Nouvelle facture</Link>, puis reviens enregistrer le paiement.</div>}</Card><Card className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="py-2">Date</th><th>Client</th><th>Facture</th><th>Montant</th><th>Mode</th><th className="text-right">Actions</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id} className="border-t"><td className="py-3">{payment.paidAt.toLocaleDateString("fr-FR")}</td><td>{payment.client.legalName}</td><td>{payment.invoice.number}</td><td>{formatCurrency(Number(payment.amount))}</td><td>{payment.method}</td><td className="text-right"><form action={deletePayment}><input type="hidden" name="id" value={payment.id} /><ConfirmSubmitButton message="Supprimer ce paiement et recalculer la facture ?" variant="ghost" className="h-8 px-2 text-xs text-red-600">Supprimer</ConfirmSubmitButton></form></td></tr>)}</tbody></table></Card></div>;
}
