import { ConfirmSubmitButton } from "@/components/confirm-submit-button";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createExpense, deleteAllExpenses, deleteExpense } from "@/features/expenses/actions";
import { prisma } from "@/lib/prisma";
import { formatCurrency } from "@/lib/utils";

export default async function ExpensesPage() {
  const [expenses, categories] = await Promise.all([prisma.expense.findMany({ include: { category: true }, orderBy: { date: "desc" } }), prisma.category.findMany({ where: { kind: "EXPENSE" } })]);
  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">Dépenses</h1><p className="text-muted-foreground">Achats, TVA déductible et justificatifs.</p></div><form action={deleteAllExpenses}><ConfirmSubmitButton message="Supprimer toutes les dépenses et transactions liées ?" variant="secondary" className="text-red-600">Supprimer toutes</ConfirmSubmitButton></form></div><Card><form action={createExpense} className="grid gap-3 md:grid-cols-6"><Input name="date" type="date" required /><Input name="vendor" placeholder="Fournisseur" required /><Input name="description" placeholder="Description" required /><select name="categoryId" className="h-10 rounded-lg border bg-card px-3 text-sm"><option value="">Catégorie</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><Input name="amountExcludingTax" type="number" step="0.01" placeholder="HT" required /><Input name="taxAmount" type="number" step="0.01" placeholder="TVA" /><Input name="paymentMethod" placeholder="Moyen paiement" defaultValue="Carte" required /><Button className="md:col-span-5">Créer la dépense</Button></form></Card><Card className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="py-2">Date</th><th>Fournisseur</th><th>Description</th><th>Catégorie</th><th>TTC</th><th className="text-right">Actions</th></tr></thead><tbody>{expenses.map((expense) => <tr key={expense.id} className="border-t"><td className="py-3">{expense.date.toLocaleDateString("fr-FR")}</td><td>{expense.vendor}</td><td>{expense.description}</td><td>{expense.category?.name ?? "-"}</td><td>{formatCurrency(Number(expense.totalAmount))}</td><td className="text-right"><form action={deleteExpense}><input type="hidden" name="id" value={expense.id} /><ConfirmSubmitButton message="Supprimer cette dépense et sa transaction liée ?" variant="ghost" className="h-8 px-2 text-xs text-red-600">Supprimer</ConfirmSubmitButton></form></td></tr>)}</tbody></table></Card></div>;
}
