import { RecurringExpenseStatus } from "@prisma/client";
import { ConfirmSubmitButton } from "@/components/confirm-submit-button";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createRecurringExpense, deleteRecurringExpense, generateCurrentMonthRecurringExpenses, updateRecurringExpenseStatus } from "@/features/recurring-expenses/actions";
import { prisma } from "@/lib/prisma";
import { formatCurrency } from "@/lib/utils";

export default async function RecurringExpensesPage() {
  const [recurringExpenses, categories] = await Promise.all([
    prisma.recurringExpense.findMany({ include: { category: true }, orderBy: { createdAt: "desc" } }),
    prisma.category.findMany({ where: { kind: "EXPENSE" }, orderBy: { name: "asc" } })
  ]);

  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">Dépenses récurrentes</h1><p className="text-muted-foreground">Abonnements mensuels à débiter dans les dépenses.</p></div><form action={generateCurrentMonthRecurringExpenses}><Button>Générer le mois</Button></form></div><Card><form action={createRecurringExpense} className="grid gap-3 md:grid-cols-6"><Input name="name" placeholder="Nom" required /><Input name="vendor" placeholder="Fournisseur" required /><Input name="description" placeholder="Description" required /><select name="categoryId" className="h-10 rounded-lg border bg-card px-3 text-sm"><option value="">Catégorie</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><Input name="amountExcludingTax" type="number" step="0.01" placeholder="HT mensuel" required /><Input name="taxAmount" type="number" step="0.01" placeholder="TVA" /><Input name="paymentMethod" placeholder="Moyen paiement" defaultValue="Carte" required /><Input name="startDate" type="date" /><select name="status" className="h-10 rounded-lg border bg-card px-3 text-sm">{Object.values(RecurringExpenseStatus).map((status) => <option key={status} value={status}>{status === "ACTIVE" ? "Actif" : status === "PAUSED" ? "En pause" : "Annulé"}</option>)}</select><Button className="md:col-span-3">Ajouter</Button></form></Card><Card className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="py-2">Nom</th><th>Fournisseur</th><th>Catégorie</th><th>TTC mensuel</th><th>Prochain débit</th><th>Statut</th><th className="text-right">Actions</th></tr></thead><tbody>{recurringExpenses.map((expense) => <tr key={expense.id} className="border-t"><td className="py-3 font-medium">{expense.name}</td><td>{expense.vendor}</td><td>{expense.category?.name ?? "-"}</td><td>{formatCurrency(Number(expense.totalAmount))}</td><td>{expense.nextRunAt.toLocaleDateString("fr-FR")}</td><td><form action={updateRecurringExpenseStatus} className="flex gap-2"><input type="hidden" name="id" value={expense.id} /><select name="status" defaultValue={expense.status} className="h-8 rounded-lg border bg-card px-2 text-xs">{Object.values(RecurringExpenseStatus).map((status) => <option key={status} value={status}>{status === "ACTIVE" ? "Actif" : status === "PAUSED" ? "En pause" : "Annulé"}</option>)}</select><button className="rounded-lg border px-2 text-xs hover:bg-muted">OK</button></form></td><td className="text-right"><form action={deleteRecurringExpense}><input type="hidden" name="id" value={expense.id} /><ConfirmSubmitButton message="Supprimer cette dépense récurrente ? Les dépenses déjà générées restent dans l'historique." variant="ghost" className="h-8 px-2 text-xs text-red-600">Supprimer</ConfirmSubmitButton></form></td></tr>)}</tbody></table></Card></div>;
}
